export TEMPLATE_ROOT_DIR=TEMPLATE_PREFIX
export TEMPLATE_INCLUDEDIR=${TEMPLATE_ROOT_DIR}/include
export TEMPLATE_LIBRARYDIR=${TEMPLATE_ROOT_DIR}/lib
export LD_LIBRARY_PATH=${TEMPLATE_LIBRARYDIR}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
# export PATH=${TEMPLATE_ROOT_DIR}/bin${PATH:+:${PATH}}
# export PKG_CONFIG_PATH=${TEMPLATE_LIBRARYDIR}${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
